export const translations = {
  English: {
    dashboard: "Student Dashboard",
    overview: "Overview",
    courses: "Courses",
    aiTutor: "AI Tutor",
    quizzes: "Quizzes",
    certificates: "Certificates",
    settings: "Settings",
    logout: "Logout",
    recentActivity: "Recent Activity",
    enrolledModules: "Enrolled Modules & Performance",
    course: "Course",
    progress: "Progress",
    status: "Status",
    action: "Action",
    completed: "Completed",
    inProgress: "In Progress",
    view: "View",
    resume: "Resume",
    coursesEnrolled: "Courses Enrolled",
    overallProgress: "Overall Progress",
    certificatesEarned: "Certificates Earned",
    averageQuizScore: "Average Quiz Score"
  },

  Tamil: {
    dashboard: "மாணவர் டாஷ்போர்டு",
    overview: "மேலோட்டம்",
    courses: "பாடநெறிகள்",
    aiTutor: "AI ஆசிரியர்",
    quizzes: "வினாடி வினாக்கள்",
    certificates: "சான்றிதழ்கள்",
    settings: "அமைப்புகள்",
    logout: "வெளியேறு",
    recentActivity: "சமீபத்திய செயல்பாடுகள்",
    enrolledModules: "பதிவுசெய்யப்பட்ட பாடங்கள் மற்றும் செயல்திறன்",
    course: "பாடநெறி",
    progress: "முன்னேற்றம்",
    status: "நிலை",
    action: "செயல்",
    completed: "முடிக்கப்பட்டது",
    inProgress: "முன்னேற்றத்தில் உள்ளது",
    view: "பார்க்க",
    resume: "தொடரவும்",
    coursesEnrolled: "பதிவுசெய்யப்பட்ட பாடநெறிகள்",
    overallProgress: "மொத்த முன்னேற்றம்",
    certificatesEarned: "பெற்ற சான்றிதழ்கள்",
    averageQuizScore: "சராசரி வினாடி வினா மதிப்பெண்"
  },

  Malayalam: {
    dashboard: "വിദ്യാർത്ഥി ഡാഷ്ബോർഡ്",
    overview: "അവലോകനം",
    courses: "കോഴ്സുകൾ",
    aiTutor: "AI അധ്യാപകൻ",
    quizzes: "ക്വിസുകൾ",
    certificates: "സർട്ടിഫിക്കറ്റുകൾ",
    settings: "ക്രമീകരണങ്ങൾ",
    logout: "ലോഗൗട്ട്",
    recentActivity: "സമീപകാല പ്രവർത്തനങ്ങൾ",
    enrolledModules: "എൻറോൾ ചെയ്ത മോഡ്യൂളുകളും പ്രകടനവും",
    course: "കോഴ്സ്",
    progress: "പുരോഗതി",
    status: "നില",
    action: "പ്രവർത്തനം",
    completed: "പൂർത്തിയായി",
    inProgress: "പുരോഗതിയിൽ",
    view: "കാണുക",
    resume: "തുടരുക",
    coursesEnrolled: "എൻറോൾ ചെയ്ത കോഴ്സുകൾ",
    overallProgress: "മൊത്തത്തിലുള്ള പുരോഗതി",
    certificatesEarned: "ലഭിച്ച സർട്ടിഫിക്കറ്റുകൾ",
    averageQuizScore: "ശരാശരി ക്വിസ് സ്കോർ"
  },

  Telugu: {
    dashboard: "విద్యార్థి డాష్‌బోర్డ్",
    overview: "అవలోకనం",
    courses: "కోర్సులు",
    aiTutor: "AI ట్యూటర్",
    quizzes: "క్విజ్‌లు",
    certificates: "సర్టిఫికెట్లు",
    settings: "సెట్టింగ్‌లు",
    logout: "లాగ్ అవుట్",
    recentActivity: "ఇటీవలి కార్యకలాపాలు",
    enrolledModules: "నమోదైన మాడ్యూల్స్ మరియు పనితీరు",
    course: "కోర్సు",
    progress: "పురోగతి",
    status: "స్థితి",
    action: "చర్య",
    completed: "పూర్తయింది",
    inProgress: "కొనసాగుతోంది",
    view: "చూడండి",
    resume: "కొనసాగించండి",
    coursesEnrolled: "నమోదైన కోర్సులు",
    overallProgress: "మొత్తం పురోగతి",
    certificatesEarned: "పొందిన సర్టిఫికెట్లు",
    averageQuizScore: "సగటు క్విజ్ స్కోర్"
  },

  Kannada: {
    dashboard: "ವಿದ್ಯಾರ್ಥಿ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    overview: "ಅವಲೋಕನ",
    courses: "ಕೋರ್ಸ್‌ಗಳು",
    aiTutor: "AI ಶಿಕ್ಷಕ",
    quizzes: "ಕ್ವಿಜ್‌ಗಳು",
    certificates: "ಪ್ರಮಾಣಪತ್ರಗಳು",
    settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    logout: "ಲಾಗ್ ಔಟ್",
    recentActivity: "ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ",
    enrolledModules: "ನೋಂದಾಯಿತ ಮಾಡ್ಯೂಲ್‌ಗಳು ಮತ್ತು ಕಾರ್ಯಕ್ಷಮತೆ",
    course: "ಕೋರ್ಸ್",
    progress: "ಪ್ರಗತಿ",
    status: "ಸ್ಥಿತಿ",
    action: "ಕ್ರಿಯೆ",
    completed: "ಪೂರ್ಣಗೊಂಡಿದೆ",
    inProgress: "ಪ್ರಗತಿಯಲ್ಲಿದೆ",
    view: "ವೀಕ್ಷಿಸಿ",
    resume: "ಮುಂದುವರಿಸಿ",
    coursesEnrolled: "ನೋಂದಾಯಿತ ಕೋರ್ಸ್‌ಗಳು",
    overallProgress: "ಒಟ್ಟು ಪ್ರಗತಿ",
    certificatesEarned: "ಗಳಿಸಿದ ಪ್ರಮಾಣಪತ್ರಗಳು",
    averageQuizScore: "ಸರಾಸರಿ ಕ್ವಿಜ್ ಸ್ಕೋರ್"
  },

  Hindi: {
    dashboard: "छात्र डैशबोर्ड",
    overview: "अवलोकन",
    courses: "पाठ्यक्रम",
    aiTutor: "AI ट्यूटर",
    quizzes: "क्विज़",
    certificates: "प्रमाणपत्र",
    settings: "सेटिंग्स",
    logout: "लॉग आउट",
    recentActivity: "हाल की गतिविधि",
    enrolledModules: "नामांकित मॉड्यूल और प्रदर्शन",
    course: "पाठ्यक्रम",
    progress: "प्रगति",
    status: "स्थिति",
    action: "कार्य",
    completed: "पूर्ण",
    inProgress: "प्रगति में",
    view: "देखें",
    resume: "जारी रखें",
    coursesEnrolled: "नामांकित पाठ्यक्रम",
    overallProgress: "कुल प्रगति",
    certificatesEarned: "प्राप्त प्रमाणपत्र",
    averageQuizScore: "औसत क्विज़ स्कोर"
  },

  Korean: {
    dashboard: "학생 대시보드",
    overview: "개요",
    courses: "강좌",
    aiTutor: "AI 튜터",
    quizzes: "퀴즈",
    certificates: "수료증",
    settings: "설정",
    logout: "로그아웃",
    recentActivity: "최근 활동",
    enrolledModules: "수강 모듈 및 성과",
    course: "강좌",
    progress: "진행률",
    status: "상태",
    action: "작업",
    completed: "완료",
    inProgress: "진행 중",
    view: "보기",
    resume: "계속하기",
    coursesEnrolled: "수강 중인 강좌",
    overallProgress: "전체 진행률",
    certificatesEarned: "취득한 수료증",
    averageQuizScore: "평균 퀴즈 점수"
  }
};